### PR TITLE
Fix markup

### LINKED ISSUE #3: TypeError when using together with plone4.csrffixes
when invoking the context menu on any calendar item on a plone4 site with plone4.csrffixes installed an error occurs:

```
  File "~/.buildout/eggs/plone4.csrffixes-1.1-py2.7.egg/plone4/csrffixes/transform.py", line 108, in transformIterable
    return self.transform(result, encoding)
  File "~/.buildout/eggs/plone4.csrffixes-1.1-py2.7.egg/plone4/csrffixes/transform.py", line 200, in transform
    url, self.request, manager=self.key_manager)
  File "lxml.etree.pyx", line 2161, in lxml.etree._Attrib.__setitem__ (src/lxml/lxml.etree.c:48586)
  File "apihelpers.pxi", line 563, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:15481)
  File "apihelpers.pxi", line 1367, in lxml.etree._utf8 (src/lxml/lxml.etree.c:22126)
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

i'll provide a PR soon

### PR DESCRIPTION
**Pull request by frisi**
hi @rnixx 
this PR fixes #3 

could you please review, merge and cut a new release (or add me as a maintainer on pypi)
thanks a lot

### CODE REVIEW

**Comment by frisi** [comment]
@Martronic-SA maybe you are in charge to review merge this?

if you add me as a maintainer on pypi i'll happily merge this and cut a new release (@rnixx)

**Comment by Martronic-SA** [comment]
Hello!
What is you login on pypi?
I've already added a rnix as maintainer and owner. ?

**Comment by frisi** [comment]
hi @Martronic-SA  - my pypi user frisi.
robert (@rnixx) seems busy at the moment ;-P

**Comment by frisi** [comment]
@Martronic-SA  - could you know pypi user  fmoret and ask him/her to grant me permissions to upload a new release?

**Comment by Martronic-SA** [comment]
That's me! ok I've added frisi to the maintainers.

**Pull request merged**
